name: flutter_channel_practice
version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: '>=2.0.4'

dependencies:
  flutter:
    sdk: flutter
  hooks_riverpod: ^0.14.0
  freezed_annotation: ^0.14.0
  draw_your_image: ^0.2.0
  flutter_signature_view: ^2.0.0

dev_dependencies:
  build_runner: ^1.12.2
  freezed: ^0.14.0
  effective_dart:

flutter:
  uses-material-design: true
